version: '2'

services:
    geoserver1:
        image: geoserver_amigo:latest
        ports:
          - 9091:9090
        volumes:
          - geoserver_data_volume2:/opt/tomcat/webapps/geoserver/data
          - /home/victor:/mnt

#    geoserver2:
#        image: geoserver_amigo
#        ports:
#          - 9092:9090
#        volumes:
#          - geoserver_data_volume2:/opt/tomcat/webapps/geoserver/data
#          - /home/victor:/mnt
#
#    geoserver3:
#        image: geoserver_amigo
#        ports:
#          - 9093:9090
#        volumes:
#          - geoserver_data_volume2:/opt/tomcat/webapps/geoserver/data
#          - /home/victor:/mnt

    accumulo-master:
      image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
      command: master --auto-init
      environment:
        HADOOP_USER_NAME: hdfs
        HADOOP_MASTER_ADDRESS: gold-1
        ZOOKEEPERS: gold-1
        INSTANCE_NAME: accumulo4
        ACCUMULO_PASSWORD: lionstone
        MASTER_XMX: 32G
      network_mode: "host"

    accumulo-monitor:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: monitor
        environment:
          HADOOP_USER_NAME: hdfs
          HADOOP_MASTER_ADDRESS: gold-1
          ZOOKEEPERS: gold-1
          INSTANCE_NAME: accumulo4
          MONITOR_XMX: 8G
        network_mode: "host"
        ports:
          - 50095:50095
        depends_on:
          - accumulo-master

    accumulo-tserver:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: tserver
        environment:
          HADOOP_USER_NAME: hdfs
          HADOOP_MASTER_ADDRESS: gold-1
          ZOOKEEPERS: gold-1
          INSTANCE_NAME: accumulo4
          TSERVER_XMX: 32G
          TSERVER_CACHE_DATA_SIZE: 10G
          TSERVER_CACHE_INDEX_SIZE: 10G
        network_mode: "host"
        depends_on:
          - accumulo-master
        volumes:
          - tserver_data_volume:/opt/accumulo/lib/ext

    accumulo-gc:
        image: quay.io/geomesa/accumulo-geomesa:geomesa-1.3.2-accumulo-1.7.3
        command: gc
        environment:
          HADOOP_USER_NAME: hdfs
          HADOOP_MASTER_ADDRESS: gold-1
          ZOOKEEPERS: gold-1
          INSTANCE_NAME: accumulo4
          GC_XMX: 16G
        network_mode: "host"
        depends_on:
          - accumulo-master

volumes:
  geoserver_data_volume2:
    external: true

  tserver_data_volume:
    external: true
